name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Create Release
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Create Release for Tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/norah1to/setup-cli/main/CHANGELOG.md) for details.
